### ISSUE TITLE
/usr/bin/ld: cannot find -lBoost::json

### ISSUE THREAD

**Issue by chasglim** [encryptogroup/MOTION2NX#3]
Hello, I have this problem while compiling, how can I solve it.

`[ 39%] Building CXX object src/motioncore/CMakeFiles/motion.dir/statistics/analysis.cpp.o
[ 39%] Building CXX object src/motioncore/CMakeFiles/motion.dir/utility/fiber_thread_pool/fiber_thread_pool.cpp.o
[ 40%] Building CXX object src/motioncore/CMakeFiles/motion.dir/utility/fiber_thread_pool/pooled_work_stealing.cpp.o
[ 40%] Building CXX object src/motioncore/CMakeFiles/motion.dir/utility/logger.cpp.o
[ 41%] Building CXX object src/motioncore/CMakeFiles/motion.dir/utility/runtime_info.cpp.o
[ 42%] Building CXX object src/motioncore/CMakeFiles/motion.dir/wire/bmr_wire.cpp.o
[ 42%] Building CXX object src/motioncore/CMakeFiles/motion.dir/wire/wire.cpp.o
[ 42%] Building CXX object src/motioncore/CMakeFiles/motion.dir/version.cpp.o
[ 43%] Linking CXX static library ../../lib/libmotion.a
[ 62%] Built target motion
[ 63%] Built target gtest
[ 64%] Built target gtest_main
[ 65%] Linking CXX executable ../../bin/motiontest
/usr/bin/ld: cannot find -lBoost::json
collect2: error: ld returned 1 exit status
make[2]: *** [src/test/CMakeFiles/motiontest.dir/build.make:577: bin/motiontest] Error 1
make[1]: *** [CMakeFiles/Makefile2:71`

**Comment by SuviSree** [comment]
I also have this same boost error while compiling.

**Comment by lenerd** [comment]
Hi all,

I noticed that the Boost version which is automatically downloaded and built if no suitable version is found on the system was way too old. I have updated it to the current release and also fixed some other linking problems.

Please let me know if the latest commits fix your problems. If the issue persists, please tell me which OS and which versions of CMake, Boost you use.

**Comment by SuviSree** [comment]
it does fix for me. thank u.

**Comment by chasglim** [comment]
it does fix for me. thank u.

**Comment by lenerd** [comment]
Great! :)
